version: '2'
services:
  web:
    build: .
    command: /bin/bash
    container_name: jolly
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - .:/myapp
    networks:
      app_net:
        ipv4_address: 172.4.0.24
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.4.0.0/24
        gateway: 172.4.0.1
        